name: rjafecit
services:
  web:
    container_name: rjafecit
    build:
      context: ..
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env.docker
    depends_on:
      - backend
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
  backend:
    build: ../backend
    ports:
      - "8080:8080"
